### ISSUE TITLE
unable to install cdk-library-certbot v1.1.297

### ISSUE THREAD

**Issue by stackblaze** [RenovoSolutions/cdk-library-certbot#865]
**Describe the bug**
Seeing an error when attempting to install `v1.1.297`, works with older versions. 
Env Version  `Node.js v19.8.1.`  `NPM 9.5.1`
**To Reproduce**
1. `npm install -g aws-cdk`
2. `mkdir cert_bot`
3. `cd cert_bot`
4. `npm i @renovosolutions/cdk-library-certbot`

**Expected behavior**
Installs without errors 
**Screenshots**
![image](https://user-images.githubusercontent.com/119256201/236312394-1e8006fb-8bf8-4823-861b-fed99ad3ce3d.png)

**Logs**
```
0 verbose cli /home/linux/.nvm/versions/node/v19.8.1/bin/node /home/linux/.nvm/versions/node/v19.8.1/bin/npm
1 info using npm@9.5.1
2 info using node@v19.8.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/linux/certbot/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/linux/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/linux/.nvm/versions/node/v19.8.1/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i @renovosolutions/cdk-library-certbot@1.1.296
21 verbose argv "i" "@renovosolutions/cdk-library-certbot@1.1.296"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/linux/.npm/_logs/2023-05-04T19_39_25_045Z-
26 verbose logfile /home/linux/.npm/_logs/2023-05-04T19_39_25_045Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 19ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 157ms
34 timing idealTree:userRequests Completed in 2ms
35 silly idealTree buildDeps
36 silly fetch manifest @renovosolutions/cdk-library-certbot@1.1.296
37 timing arborist:ctor Completed in 0ms
38 http fetch GET 200 https://registry.npmjs.org/@renovosolutions%2fcdk-library-certbot 142ms (cache hit)
39 silly fetch manifest constructs@^10.0.0
40 http fetch GET 200 https://registry.npmjs.org/constructs 17ms (cache hit)
41 silly fetch manifest constructs@^3.2.27
42 timing idealTree Completed in 364ms
43 timing command:i Completed in 372ms
44 verbose stack Error: unable to resolve dependency tree
44 verbose stack     at [failPeerConflict] (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
44 verbose stack     at [loadPeerSet] (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
44 verbose stack     at async [buildDepStep] (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
44 verbose stack     at async Arborist.buildIdealTree (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
44 verbose stack     at async Promise.all (index 1)
44 verbose stack     at async Arborist.reify (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
44 verbose stack     at async Install.exec (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/lib/commands/install.js:146:5)
44 verbose stack     at async module.exports (/home/linux/.nvm/versions/node/v19.8.1/lib/node_modules/npm/lib/cli.js:134:5)
45 verbose cwd /home/linux/certbot
46 verbose Linux 4.4.0-19041-Microsoft
47 verbose node v19.8.1
48 verbose npm  v9.5.1
49 error code ERESOLVE
50 error ERESOLVE unable to resolve dependency tree
51 error
52 error While resolving: [1mcertbot[22m@[1m0.1.0[22m
52 error Found: [1mconstructs[22m@[1m10.2.15[22m[2m[22m
52 error [2mnode_modules/constructs[22m
52 error   [1mconstructs[22m@"[1m^10.0.0[22m" from the root project
52 error
52 error Could not resolve dependency:
52 error [35mpeer[39m [1mconstructs[22m@"[1m^3.2.27[22m" from [1m@renovosolutions/cdk-library-certbot[22m@[1m1.1.296[22m[2m[22m
52 error [2mnode_modules/@renovosolutions/cdk-library-certbot[22m
52 error   [1m@renovosolutions/cdk-library-certbot[22m@"[1m1.1.296[22m" from the root project
52 error
52 error Fix the upstream dependency conflict, or retry
52 error this command with --force or --legacy-peer-deps
52 error to accept an incorrect (and potentially broken) dependency resolution.
53 error
53 error
53 error For a full report see:
53 error /home/linux/.npm/_logs/2023-05-04T19_39_25_045Z-eresolve-report.txt
54 verbose exit 1
55 timing npm Completed in 419ms
56 verbose unfinished npm timer reify 1683229165083
57 verbose unfinished npm timer reify:loadTrees 1683229165087
58 verbose unfinished npm timer idealTree:buildDeps 1683229165247
59 verbose unfinished npm timer idealTree:#root 1683229165247
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /home/linux/.npm/_logs/2023-05-04T19_39_25_045Z-debug-0.log

```

**Additional context**

**Comment by bmiller08** [comment]
Confirmed my suspicion. Try `npm i @renovosolutions/cdk-library-certbot@^2` instead to be sure you are getting version 2 or greater of the library and it should work fine.

**Comment by bmiller08** [comment]
Have not heard back so I am closing this. Feel free to respond if it needs re-opened.
