### ISSUE TITLE
Wildcard certificate support broken

### ISSUE THREAD

**Issue by bashtoni** [RenovoSolutions/cdk-library-certbot#916]
I tried to issue a wildcard certificate. The issuance seems to have worked OK, but then:

```
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/config-dir/live/*.redacted.com.au/cert.pem'
Traceback (most recent call last):
  File "/var/task/index.py", line 229, in handler
    cert = provision_cert(os.environ['LETSENCRYPT_EMAIL'], domains, storage_method, os.environ['KEY_TYPE'])
  File "/var/task/index.py", line 116, in provision_cert
    'certificate': read_and_delete_file(path + 'cert.pem', 'cert.pem', storage_method),
  File "/var/task/index.py", line 69, in read_and_delete_file
    with open(path, 'rb') as file:
```

**Comment by zlatkoc** [comment]
Use:

```
let domains = ["redacted.com.au", "*.redacted.com.au"];
...
new Certbot(this, "cert", {
    letsencryptDomains: domains.join(","),
    ...
});
```
